language: node_js
node_js:
  - "11.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli firebase-tools
script:
  - npm install
  - npm run build
  - firebase use default
  - firebase deploy --only hosting --token "1//0doQs4FiL1D_ZCgYIARAAGA0SNwF-L9IrN-bj-LRG5IyxnpiJzvUGyAv2CgM8wTG_BTy9YE2LMbqVxAWf6OlPx1h4OA5htMGaXJw"
