language: node_js
node_js:
  - "11.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli firebase-tools
script:
  - npm install
  - npm run build --prod
  - firebase deploy --only hosting --token "1//0dacifTJOMAgACgYIARAAGA0SNwF-L9IrcEEx514QYp9l7EbaRWxt6SOS3UT2ujQL3w-8T3A-Ipbvs1s4Zv7XpPSsDzcH_IqPkqg"
branches:
  only:
    - master